# Generated by Django 5.2 on 2025-04-03 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='node',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'node'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.productcategory'),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
