# Generated by Django 4.2.20 on 2025-04-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerdemand',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'node'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='distributor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='node',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'node'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='retailerdemand',
            index=models.Index(fields=['retailer'], name='marketplace_retaile_cc9dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerdemand',
            index=models.Index(fields=['product'], name='marketplace_product_82e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerdemand',
            index=models.Index(fields=['fulfilled'], name='marketplace_fulfill_bf8b6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'retailer')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='marketplace_name_c7bd47_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='marketplace_categor_0fd450_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['distributor'], name='marketplace_distrib_026f71_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['retailer'], name='marketplace_retaile_dc98c7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['node'], name='marketplace_node_id_411b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='marketplace_status_6b27f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='marketplace_payment_71a995_idx'),
        ),
    ]
