# Generated by Django 4.2.20 on 2025-04-12 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('primary', 'Primary Node'), ('sub', 'Sub Node')], max_length=20)),
                ('coverage_area', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Storage capacity in cubic meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('established_date', models.DateField(auto_now_add=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('service_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['-established_date'],
            },
        ),
        migrations.CreateModel(
            name='NodeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('threshold', models.DecimalField(decimal_places=2, default=5, help_text='Minimum quantity before restock alert', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Node Inventory',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_route', models.JSONField()),
                ('optimization_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_savings', models.DecimalField(decimal_places=2, help_text='Estimated savings in percentage', max_digits=10)),
                ('actual_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Actual realized savings', max_digits=10, null=True)),
                ('route_distance', models.DecimalField(decimal_places=2, default=0.0, help_text='Total distance in kilometers', max_digits=10)),
                ('execution_time', models.DurationField(blank=True, help_text='Actual time taken to complete the route', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_routes', to='nodes.node')),
            ],
            options={
                'verbose_name_plural': 'Route Optimizations',
                'ordering': ['-optimization_date'],
            },
        ),
        migrations.CreateModel(
            name='NodePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orders_processed', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retailers_served', models.PositiveIntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of orders fulfilled successfully', max_digits=5)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='nodes.node')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NodeMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('downtime_duration', models.DurationField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='nodes.node')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
