# Generated by Django 5.2 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('primary', 'Primary Node'), ('sub', 'Sub Node')], max_length=20)),
                ('coverage_area', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Storage capacity in cubic meters', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orders_processed', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retailers_served', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_route', models.JSONField()),
                ('optimization_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_savings', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
