# Generated by Django 5.2 on 2025-04-03 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='operator',
            field=models.OneToOneField(limit_choices_to={'user_type': 'node'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nodes', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='nodeinventory',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node'),
        ),
        migrations.AddField(
            model_name='nodeinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='nodeperformance',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node'),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeinventory',
            unique_together={('node', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeperformance',
            unique_together={('node', 'date')},
        ),
    ]
