# Generated by Django 4.2.20 on 2025-04-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemaintenancelog',
            name='performed_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodeinventory',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='nodeinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_inventory', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='node',
            name='operator',
            field=models.OneToOneField(limit_choices_to={'user_type': 'node'}, on_delete=django.db.models.deletion.CASCADE, related_name='operated_node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nodes', to='nodes.node'),
        ),
        migrations.AddIndex(
            model_name='nodeperformance',
            index=models.Index(fields=['date'], name='nodes_nodep_date_a83c5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeperformance',
            unique_together={('node', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeinventory',
            unique_together={('node', 'product')},
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='nodes_node_node_ty_c259da_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['status'], name='nodes_node_status_92bac2_idx'),
        ),
    ]
