# Generated by Django 4.2.20 on 2025-04-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='favorite_nodes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_dashboards', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='preferred_products',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_dashboards', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='recent_orders',
            field=models.ManyToManyField(blank=True, related_name='recent_in_dashboards', to='marketplace.order'),
        ),
    ]
