# Generated by Django 5.2 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='favorite_nodes',
            field=models.ManyToManyField(blank=True, to='nodes.node'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='preferred_products',
            field=models.ManyToManyField(blank=True, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='recent_orders',
            field=models.ManyToManyField(blank=True, to='marketplace.order'),
        ),
    ]
