# Generated by Django 5.2 on 2025-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardanalytics',
            name='ai_generated_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='ai_insights_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
